### ISSUE TITLE
[BUG] Broken Link for bundle-workflow

### ISSUE THREAD

**Issue by macohen** [opensearch-project/.github#101]
### What is the bug?
https://github.com/opensearch-project/.github/blob/main/RELEASING.md#releasing has a link to [bundle-workflow](https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/README.md) that is broken. This also shows up in other repos that have copies of the RELEASING.md file.

### How can one reproduce the bug?
Go to https://github.com/opensearch-project/.github/blob/main/RELEASING.md#releasing. In the Releasing section, the first bullet has "bundle-workflow" linked to https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/README.md which produces a 404. 

### What is the expected behavior?
Not sure what a valid link is here.

### What is your host/environment?
N/A

**Comment by dblock** [comment]
@macohen Please PR a fix. Likely faster than opening this issue :)

**Comment by macohen** [comment]
Would love to, but I don't know where the link should actually go! Any idea?

**Comment by dblock** [comment]
Oh! This is old. Delete the entire contents of this section and point to https://github.com/opensearch-project/opensearch-build#releasing-opensearch
