### ISSUE TITLE
[BUG] Banner image path is incorrrect

### ISSUE THREAD

**Issue by ps48** [opensearch-project/.github#124]
### What is the bug?
Banner image path is incorrect, leading it to be blank on github home.

### How can one reproduce the bug?
Visit Opensearch-project homage on github: https://github.com/opensearch-project

### Screenshot
<img width="1429" alt="Screen Shot 2023-01-07 at 11 13 04 AM" src="https://user-images.githubusercontent.com/4348487/211166838-2abdb35f-937b-4279-a054-2115ca8e291a.png">

**Comment by ps48** [comment]
PR in progress closing this.

**Comment by dblock** [comment]
Reopening until that's fixed.
