### ISSUE TITLE
[PROPOSAL] Adopt working group for Project-wide changes

### ISSUE THREAD

**Issue by peternied** [opensearch-project/.github#128]
### What are you proposing?
Create self-selecting working group, whose members make proposals and then vote on them to affect change across the OpenSearch Project.

### What users have asked for this feature?
@joshuarrrr

### What problems are you trying to solve?
Individual member repository of OpenSearch Project have a large amount of autonomy and the OpenSearch Project has issues that should be addressed across those member repositories.  Ensuring vibrate debate can occurs and opportunities for perspective is critical for successful adoption of cross project solutions.

- When a project-wide problem is identified, OpenSearch Project members and contributors want to know what that problem is.
- When a group is being created, OpenSearch Project members and contributors want to join that group if they are interested in the problem.
- When a group works on the project-wide problem, OpenSearch Project members and contributors want to see what is proposed, comment, vote for/against proposals.
- When a group has finished, OpenSearch Project members and contributors want to see the outcome of that groups work.

### What is the experience going to be?
A contributor on a issue will make a request of member repo maintainers of the OpenSearch Project for a working group to be created.  Requested maintainers can agree or disagree that the issue is project-wide and a working group should be created.  After three repos have agreed, the contributor will make a comment on the issue for those interested to join a working group.

The working group will collaborate establishing tenants and create a working group issue in the opensearch-project/.github repository for tracking.

On the working group issue, and the members of the working group will document the current state of proposals and the next set of proposals to consider.  At a cadence (weekly), proposals will be created, reviewed, and voted on.  After the working group accepts a proposals, new requests for proposal will go out for the next phase of work. 

When the working group has completed its objective, it will create a blog post on the opensearch-project/project-website capturing its topic, members, and result.

### Why should it be built? Any reason not to?
We have a mechanism for project-wide change, Campaigns, these serve as top down efforts and are associated with a release deliverables.  Campaigns have been used for a number of different issues, they have been challenging for topics with diverse opinions, another option is needed.  Additionally, a working group might propose campaign(s) to achieve their objective.

If there is no interest in following the process we should not attempt to use it

### What will it take to execute?
OpenSearch Project should make a working group to try this process out.  @joshuarrrr has offered to lead this effort.

### Any remaining open questions?
As proposal are made, they should be stored somewhere.  As working groups are project-wide, having those proposals be created as pull requests open for comment and merged on working group agreement is known tooling, this would make the `.github` repository an ideal central store.

Do the maintainers of `.github` think that this project is an appropriate place and would be willing to merge pull requests in this repository?

**Comment by peternied** [comment]
@CEHENKLE What do you think?

**Comment by peternied** [comment]
@dblock @mch2 @saratvemulapalli any thoughts?

**Comment by saratvemulapalli** [comment]
@peternied sounds like a good start. 
What do you want to get done as part of this proposal?

**Comment by dblock** [comment]
I think this repo is a good place for project-wide initiatives. Another place we thought about would be https://github.com/opensearch-project/project-meta, but that didn't stick.

Other than documenting a suggested process, do we need voting? Anyone can open an issue in .github and call for a "working group". I think the real test comes when we want to adopt an org wide thing, which probably should be left to maintainers of .github (which we can grow organically from existing maintainers).

**Comment by peternied** [comment]
Note; I don't have an example where we would need this level of codification.  I'm going to close out this issue, we can always revisit if we want to take up documenting this more.
