### ISSUE TITLE
[DOC] Create onboarding document for developers new to the project

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/.github#131]
### Is your feature request related to a problem?

We have lots of useful information spread throughout the documentation site, this repo, and project repositories. But we don't have a single point of entry to organize that info into an onboarding plan. I propose a new document that provides new developers a curated list of links and resources for understanding key project concepts.

### What solution would you like?

The document is for any developer who’s interested in contributing code (features and fixes) to one of the OpenSearch open source project repositories for the first time. No knowledge of the OpenSearch software or project required. It should provide everything necessary to:

1. Understand the key concepts of the OpenSearch project and how to find additional resources
2. Set up the accounts they’ll need to contribute

### What alternatives have you considered?

While some of these links are also provided in readmes or developer guides, but those tend to be unstructured and for broad usage.

### Do you have any additional context?

The envisioned document should be mostly links and context, with minimal new content, for ease of maintenance.

**Comment by dblock** [comment]
We do have an organization README in https://github.com/opensearch-project/.github/blob/main/profile/README.md.
