### ISSUE TITLE
[PROPOSAL] Ensure all new issues have an untriaged label

### ISSUE THREAD

**Issue by dblock** [opensearch-project/.github#133]
### What are you proposing?

Ensure that all new issues carry an `untriaged` label.

### What users have asked for this feature?

We use `untriaged` as a mechanism to know that a human has looked at every new issue and classified it correctly, which is especially important for security issues. Triaging issues is documented in https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#triage-open-issues.

### What problems are you trying to solve?

Many repos either do not have an untriaged label, or new issues created don't have an `untriaged` label. This means there may be open issues that are security that nobody has looked at.

### What is the developer experience going to be?

1. Ensure the repo has an `untriaged` label. The official color for the label is `#FBCA04`.
2. Ensure a GH workflow that adds an untriaged label copied from [here](https://github.com/opensearch-project/.github/blob/main/.github/workflows/add-untriaged.yml). 

- [x] https://github.com/opensearch-project/alerting/issues/795
- [x] https://github.com/opensearch-project/alerting-dashboards-plugin/issues/482
- [x] https://github.com/opensearch-project/anomaly-detection/issues/809
- [x] https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/422
- [x] https://github.com/opensearch-project/asynchronous-search/issues/236
- [x] https://github.com/opensearch-project/common-utils/issues/358
- [x] https://github.com/opensearch-project/reporting/issues/645
- [x] https://github.com/opensearch-project/dashboards-visualizations/issues/164
- [x] https://github.com/opensearch-project/data-prepper/issues/2276
- [x] https://github.com/opensearch-project/documentation-website/issues/2879
- [x] https://github.com/opensearch-project/index-management/issues/685
- [x] https://github.com/opensearch-project/index-management-dashboards-plugin/issues/611
- [x] https://github.com/opensearch-project/job-scheduler/issues/317
- [x] https://github.com/opensearch-project/k-NN/issues/762
- [x] https://github.com/opensearch-project/logstash-output-opensearch/issues/197
- [x] https://github.com/opensearch-project/notifications/issues/617
- [x] https://github.com/opensearch-project/OpenSearch/issues/6320
- [x] https://github.com/opensearch-project/opensearch-build/issues/3202
- [x] https://github.com/opensearch-project/opensearch-cli/issues/71
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3427
- [x] https://github.com/opensearch-project/opensearch-devops/issues/112
- [x] https://github.com/opensearch-project/opensearch-plugins/issues/206
- [x] https://github.com/opensearch-project/performance-analyzer/issues/383
- [x] https://github.com/opensearch-project/performance-analyzer-rca/issues/294
- [x] https://github.com/opensearch-project/perftop/issues/65
- [x] https://github.com/opensearch-project/piped-processing-language/issues/19
- [x] https://github.com/opensearch-project/project-website/issues/1355
- [x] https://github.com/opensearch-project/security-dashboards-plugin/issues/1327
- [x] https://github.com/opensearch-project/sql/issues/1338
- [x] https://github.com/opensearch-project/opensearch-plugin-template-java/issues/50
- [x] https://github.com/opensearch-project/project-meta/issues/84
- [x] https://github.com/opensearch-project/geospatial/issues/222
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/705
- [x] https://github.com/opensearch-project/opensearch-go/issues/231
- [x] https://github.com/opensearch-project/opensearch-java/issues/364
- [x] https://github.com/opensearch-project/opensearch-py/issues/290
- [x] https://github.com/opensearch-project/opensearch-js/issues/386
- [x] https://github.com/opensearch-project/helm-charts/issues/382
- [x] https://github.com/opensearch-project/ansible-playbook/issues/115
- [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/527
- [x] https://github.com/opensearch-project/opensearch-dashboards-test-library/issues/30
- [x] https://github.com/opensearch-project/opensearch-ci/issues/250
- [x] https://github.com/opensearch-project/project-website-search/issues/45
- [x] https://github.com/opensearch-project/opensearch-dsl-py/issues/97
- [x] https://github.com/opensearch-project/opensearch-clients/issues/52
- [x] https://github.com/opensearch-project/opensearch-rs/issues/124
- [x] https://github.com/opensearch-project/opensearch-php/issues/124
- [x] https://github.com/opensearch-project/opensearch-ruby/issues/143
- [x] https://github.com/opensearch-project/ml-commons/issues/728
- [x] https://github.com/opensearch-project/opensearch-benchmark/issues/218
- [x] https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/62
- [x] https://github.com/opensearch-project/observability/issues/1409
- [x] https://github.com/opensearch-project/opensearch-oci-object-storage/issues/29
- [x] https://github.com/opensearch-project/dashboards-desktop/issues/36
- [x] https://github.com/opensearch-project/logstash-input-opensearch/issues/46
- [x] https://github.com/opensearch-project/maps/issues/38
- [x] https://github.com/opensearch-project/opensearch-api-specification/issues/78
- [x] https://github.com/opensearch-project/dashboards-anywhere/issues/152
- [x] https://github.com/opensearch-project/security-analytics/issues/325
- [x] https://github.com/opensearch-project/opensearch-catalog/issues/10
- [x] https://github.com/opensearch-project/dashboards-maps/issues/248
- [x] https://github.com/opensearch-project/i18n-plugin/issues/18
- [x] https://github.com/opensearch-project/opensearch-testcontainers/issues/68
- [x] https://github.com/opensearch-project/oui/issues/306
- [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/450
- [x] https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/410
- [x] https://github.com/opensearch-project/dashboards-docker-images/issues/11
- [x] https://github.com/opensearch-project/docker-images/issues/17
- [x] https://github.com/opensearch-project/opensearch-build-libraries/issues/141
- [x] https://github.com/opensearch-project/ux/issues/60
- [x] https://github.com/opensearch-project/opensearch-hadoop/issues/95
- [x] https://github.com/opensearch-project/spring-data-opensearch/issues/96
- [x] https://github.com/opensearch-project/neural-search/issues/112
- [x] https://github.com/opensearch-project/simple-schema/issues/70
- [x] https://github.com/opensearch-project/terraform-provider-opensearch/issues/24
- [x] https://github.com/opensearch-project/project-tools/issues/52
- [x] https://github.com/opensearch-project/opensearch-py-ml/issues/84
- [x] https://github.com/opensearch-project/opensearch-cluster-cdk/issues/13
- [x] https://github.com/opensearch-project/oui-docs-cdk/issues/9
- [x] https://github.com/opensearch-project/search-processor/issues/103
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/107
- [x] https://github.com/opensearch-project/dashboards-query-workbench/issues/42
- [x] https://github.com/opensearch-project/sql-cli/issues/11
- [x] https://github.com/opensearch-project/sql-jdbc/issues/58
- [x] https://github.com/opensearch-project/sql-odbc/issues/32
- [x] https://github.com/opensearch-project/dashboards-observability/issues/276
- [x] https://github.com/opensearch-project/dashboards-notifications/issues/14
- [x] https://github.com/opensearch-project/dashboards-reporting/issues/62
- [x] https://github.com/opensearch-project/opensearch-dashboards-sdk-js/issues/39

**Comment by dbwiddis** [comment]
The bug and issue templates at `.github` (imported by all projects by default) already apply `untriaged` labels to issues created via those templates (unless intentionally removed by the issue creator before opening the issue).  Are those workflows sufficient to meet this goal?

**Comment by dblock** [comment]
> The bug and issue templates at `.github` (imported by all projects by default) already apply `untriaged` labels to issues created via those templates (unless intentionally removed by the issue creator before opening the issue). Are those workflows sufficient to meet this goal?

It's sufficient but not robust enough. I found a number of repos (10+) without an untriaged label.

**Comment by dbwiddis** [comment]
> It's sufficient but not robust enough. I found a number of repos (10+) without such templates (deleted or not inherited), and/or no untriaged label.

Fair, but if the label exists and issues are being triaged, is that sufficient to meet the intent of this campaign?

I ask because the vast majority of issues created on our repo are by maintainers themselves, and we often intentionally remove the pre-populated untriaged label to reduce noise.  This workflow will add it back and force us to remove it again, or more likely we'll forget and we'll end up with real untriaged issues hidden amongst our future feature planning.

**Comment by dblock** [comment]
@dbwiddis up to you, but I prefer the workflow because it is more future proof

**Comment by dblock** [comment]
And we're done!
