### ISSUE TITLE
[DOCS] Improve DCO section of CONTRIBUTING.md to help contributors resolve common DCO check failures

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/.github#137]
### Is your feature request related to a problem?

Our canonical source of info about the DCO check is https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin. It provides lots of useful background and explanation, yet maintainers regularly see first time contributors stumble on this step and require multiple attempts to sign their commits correctly. We should provide guidance on how to fix.

In addition, GitHub accounts have made this less straightforward. When signing-up for a new GitHub account (as per our onboarding guide https://github.com/opensearch-project/.github/blob/main/ONBOARDING.md#github-account), the account will have "Keep my email addresses private" checked by default.

### What solution would you like?

We should update the DCO section with some troubleshooting tips for signed commits that still don't pass the DCO check automation.

Suggested text:

If you've signed your commit and it still fails the DCO check, it's likely because the email address you signed the commit with doesn't match the one on your GitHub account. There are a couple ways to solve this:

1. **If you want your email address to be public:** 1. Go to https://github.com/settings/emails and uncheck "Keep my email address private". 2. Set your commit email address following the [GitHub documentation](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git) to your primary GitHub email address.
2. **If you want your email address to remain private:** 1. Go to https://github.com/settings/emails and make sure "Keep my email address private" is checked. 2. Set your commit email address following the [GitHub documentation](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git) to the `*@users.noreply.github.com` email listed in the "Keep my email addresses private" setting.

### What alternatives have you considered?

It seems inefficient to explain this in individual repository dev guides or READMEs. We could also add it to `ONBOARDING.md` as part of the GitHub setup instructions, but it's a problem even folks with previous GitHub contribution history run into.

**Comment by dlvenable** [comment]
@joshuarrrr , We've had trouble with backports failing DCO even when the original DCO check passed. The DCO on backports sometimes doesn't find a match in the email address. Do you know if these steps remedy issues with backports?
