### ISSUE TITLE
[BUG] Pull requests to do not have quality gates.

### ISSUE THREAD

**Issue by peternied** [opensearch-project/.github#149]
#### Problem
This .github repository represents OpenSearch-Project's policies, ideals, and intentions. This repository has no quality gates other than 2 approvals and a DCO check - making the way pull requests are accepted subjective based on which maintainers/contributors first responded.

#### Expectation
There should be mechanisms to ensure a minimum quality of the changes that are accepted into this repository.

**Comment by wbeckler** [comment]
What if we increase the number of required approvals? I'm thinking that the day may come when we'll want to push something through quickly in an emergency, although I can't imagine what situation would cause that in this repo.

**Comment by dblock** [comment]
@wbeckler I believe admins can always override gates

**Comment by dblock** [comment]
@peternied shall we close this now that we do have bake time? or do you want to keep it open for more actions?

**Comment by peternied** [comment]
Yea - this looks good for now.
