### ISSUE TITLE
[PROPOSAL] Clarify Issue Types and "Last Call for Comments"

### ISSUE THREAD

**Issue by macohen** [opensearch-project/.github#164]
### What are you proposing?
We have Feature Requests and Feature Proposals documented in CONTRIBUTING.md, but we also have PROPOSALS, RFCs, FEATURE BRIEFs, BUGS. 
* Could we standardize on the types of issues?
    *  **BUG**: an unexpected result from some operation in OpenSearch that SEEMS like a bug (meaning something broken)
    *  **Feature Request**: I have an idea for new functionality, but don't have a solution. I'd like to collaborate on one or just put it out there for someone else to build.
    * Collapse these into "Feature Proposal" (clearest definition I see).
         * **RFC**: Request for Comments. - I have an idea for some implementation of a problem I have, but really want to hear from the community before doing too much.
         *  **PROPOSAL**: is this different than RFC?
         *  **Feature Proposal**: I have an idea for a feature and maybe a solution. I don't know necessarily how to build this and want to understand what others think (is this too subtle a difference from an RFC? Should this be rolled up?)
          * Are there others? 
* The GH issue should be used for commenting/discussion of the initial design. The forum should be used for long lived discussions/questions of the feature. 
* For an RFC/Proposal/Feature Proposal, let's standardize on addressing how long the issue will stay open (could be a field in the issue template and could vary on a case by case basis) and post a reminder that the issue will be closed at least a week ahead? 

### What users have asked for this feature?
@mashah - "Yes, we’re not sure both on where and how to get involved. It would be great 1/ we could put the discussion and comments for RFCs in one place (right now it seems to be distributed between forums and GitHub). 2/ Have a protocol for agreeing on and closing RFCs. A simple “last call for comments” and aiming to “close on date XX” would be helpful. 3/ perhaps have a place where we know the experimental items are ? (Again, I might have missed it.)"
https://opensearch.slack.com/archives/C04UM4D6XN2/p1685306611855109

**Comment by peternied** [comment]
@macohen I think the issue types are pretty clear, what do you want to accomplish with standardizing them?  It might be easier to see this with a PR to modify the [issue template(s)](https://github.com/opensearch-project/.github/tree/main/.github/ISSUE_TEMPLATE) that you'd like to see changed.

**Comment by macohen** [comment]
@peternied what I think I realized here is that these issue templates are pretty good and they have been updated since one of the repos I work in was created; I may have missed something, but it might be great to create issues in every repo when any .github files that could apply everywhere are updated. It's always up to the admins if the change is required (like the recently completed maintainer cleanup). If it's not required the repo maintainers can decide whether to take the change or not and close the issue.

**Comment by peternied** [comment]
@macohen When you perform the 'sync', would you mind writing that process up and creating a PR in this repo?

There are two issues around automating these processes, one [1] created by @elfisher to synchronize the issue templates and another issue for sync'ing workflow files [2].


- [1] https://github.com/opensearch-project/.github/issues/9
- [2] https://github.com/opensearch-project/.github/issues/113

**Comment by peternied** [comment]
@macohen the original proposal seems relatively complete, how would you like to use this issue or would you rather close it out?

**Comment by macohen** [comment]
Closing it out. It seems the answer is to create a process to sync .github project changes across the org. I'll track the other issues regarding automation. Thanks.
