### ISSUE TITLE
[PROPOSAL] OpenSearch Operations & Project Health meeting format

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/.github#187]
The OpenSearch team within Amazon have been holding internal maintainer meetings on holistic project needs. To increase transparency and community ownership, this meeting needs to be in the public. 

### Overview:
Strengthen the OpenSearch project by addressing maintenance and health opportunities that can enable more contributions.

Scope: Health is a broad spectrum that includes security, developer experience, maintainer experience, quality and usability standards, documentation, community wellness and safety. 

### Agenda setting:

* This is a bi-weekly meeting with topics nominated publicly or spilled from the previous meeting. 
* If you have a topic you would like discussed, propose it for addition to the next week’s agenda by doing [TBD]. 
* At the end, if there is time, we can discuss other topics. 

#### Proposals:
Anything to add to the Agenda setting?

### Agenda building: 
Where do we collaborate on building the agendas

#### Proposals:
1. Forum threads. 
    1. Pro: Easily accessible, public, can admins and moderators can edit original thread, already in-practice with Community Meetings & multiple triage meetings
    2. Con: outside of Github (if this is an issue)
2. Community repo Issues
    1. Pro: Keeps central to GitHub, public, easily accessible
    2. Con: Maintainer rights required to edit Issues, whereas forum moderator rights are easier to grant

### Tech:
Do we use Chime or Zoom?

#### Proposals:

* Zoom: fairly standard. Great moderation tools. Licensing requirements are restrictive and require a named license holder. 
* Chime: not as common. Good moderation tools. Allows anyone with “moderator code“ to act as host to each meeting. 

### Any other suggestions you have? 
We look forward to your input on this. 
thanks - [wbeckler](https://github.com/wbeckler)  & [krisfreedain](https://github.com/krisfreedain)

**Comment by reta** [comment]
Thanks a lot @krisfreedain for summing it up!

Personally, I think we should start with Zoom and:
 - Forum thread (per meeting)
 - Keep the one single Github issue with references to the forum to all past (and upcoming) meetings

Yes, it would be 2 places but I think forum is more friendly from wider collaboration (internal + external).

**Comment by apasun** [comment]
Zoom has been great with regular community meetings. Thank you doing this Kris!

**Comment by peternied** [comment]
@krisfreedain Any updates, is there a schedule for these meetings?

**Comment by krisfreedain** [comment]
Thank you all for the input. We'll work to get this scheduled ASAP

**Comment by krisfreedain** [comment]
Coming back to close this one out. We're running this meeting on a bi-weekly schedule.
