### ISSUE TITLE
PR template is not general

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/.github#2]
In the PR template it mentions 'New functionality has javadoc added.'

This would not apply to non-JVM projects (e.g. OpenSearch Dashboards (JS), OpenSearch-cli (golang), etc.)

Additionally it assumes Apache 2.0 and DCO, which is pretty safe but doesn't apply to `project-website` which is BSD 3 Clause and no DCO. For that project I've overridden the PR template since it's an exception.

**Comment by dblock** [comment]
Agreed. Do you think we should just remove that part? Feel free to PR.

**Comment by stockholmux** [comment]
Looks resolved in the PR!
