### ISSUE TITLE
Update content wrt joining the Linux Foundation

### ISSUE THREAD

**Issue by dblock** [opensearch-project/.github#216]
### Is your feature request related to a problem?

On Monday the Linux Foundation [announced](https://www.linuxfoundation.org/press/linux-foundation-announces-opensearch-software-foundation-to-foster-open-collaboration-in-search-and-analytics) the OpenSearch Software Foundation. A number of documents in this repo need updating.

### What solution would you like?

Go through all documents, figure out the correct updates with all the parties, update.

### Do you have any additional context?

https://www.linuxfoundation.org/press/linux-foundation-announces-opensearch-software-foundation-to-foster-open-collaboration-in-search-and-analytics

**Comment by peternied** [comment]
I was wondering when we'd see updates - thanks for taking this on!

**Comment by dblock** [comment]
This was https://github.com/opensearch-project/.github/pull/222, closing.
