### ISSUE TITLE
Transfer ownership of opensearch-project GitHub organization to OpenSearch Software Foundation

### ISSUE THREAD

**Issue by dblock** [opensearch-project/.github#225]
### What are you proposing?

The Linux Foundation announced the launch of the OpenSearch Software Foundation [here](https://www.linuxfoundation.org/press/linux-foundation-announces-opensearch-software-foundation-to-foster-open-collaboration-in-search-and-analytics).

Transfer ownership of the GitHub https://github.com/opensearch-project org.

**Comment by tykeal** [comment]
@dblock adding @thelinuxfoundation as an org owner is our standard mechanism of initial ownership transfer.

**Comment by tbenzies** [comment]
This has already been agreed to in the contribution agreement with Amazon.  This is for neutral ownership and also allows us to onboard into our insights tool https://lfx.linuxfoundation.org/tools/insights/.

**Comment by hyandell** [comment]
We need to discuss whether we would add @thelinuxfoundation as an org owner while the account is still within our enterprise contract; or whether we first move the account outside of our contract.

**Comment by peterzhuamazon** [comment]
The GitHub Org ownership has been transferred to Linux Foundation.
We will discuss further GitHub Request SOP later in this issue:
* https://github.com/opensearch-project/.github/issues/236

Thanks.
