### ISSUE TITLE
[GitHub Request] : access to the openseacr-project repo

### ISSUE THREAD

**Issue by Murali-Arigala** [opensearch-project/.github#242]
### What is the type of request?

Repository Management

### Details of the request

I am new SDM reporting under Rajs@ leading opensearch security analytics space. can i be granted appropriate access?
My alias is marigala@

### Additional information to support your request

I report under AOSS org

### When does this request need to be completed?

asap. we are working on release 2.19 and also patch for 2.15/17. So need access asap to address certain github issues.

### Notes

Track the progress of your request here: https://github.com/orgs/opensearch-project/projects/208/views/33.
Member of @opensearch-project/admin will take a look at the request soon.
Thanks!

**Comment by peterzhuamazon** [comment]
After offline discussion, I will request adding @Murali-Arigala to the org, as well as adding him to the triage group.

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @Murali-Arigala ,

An invite has been send you to join the org, as well as invite you to be part of triage team.
Please accept them.

Thanks.
