### ISSUE TITLE
[GitHub Request] Set the `CODECOV_TOKEN` secret on opensearch-rs

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/.github#243]
### What is the type of request?

Secret Update

### Details of the request

Please configure the [opensearch-rs](https://github.com/opensearch-project/opensearch-rs) repository secrets to include the `CODECOV_TOKEN` as specified [here](https://app.codecov.io/gh/opensearch-project/opensearch-rs/config/general).

### Additional information to support your request

Repository was previously using tokenless/OIDC for codecov uploads which is now disabled, as such test workflows are now failing.

### When does this request need to be completed?

non-urgent as repository has low PR throughput

### Notes

Track the progress of your request here: https://github.com/orgs/opensearch-project/projects/208/views/33.
Member of @opensearch-project/admin will take a look at the request soon.
Thanks!

**Comment by peterzhuamazon** [comment]
Updated CODECOV_TOKEN per request in opensearch-rs repo.

Thanks.
