### ISSUE TITLE
[GitHub Request] Add Johannes Peter to maintainers list

### ISSUE THREAD

**Issue by sstults** [opensearch-project/.github#244]
### What is the type of request?

User Permission

### Details of the request

We would like to add @JohannesDaniel to MAINTAINERS.md and CODEOWNERS.md of the [opensearch-learning-to-rank-base project](https://github.com/opensearch-project/opensearch-learning-to-rank-base) so that he can approve PRs and merge code into the main branch. A [PR](https://github.com/opensearch-project/opensearch-learning-to-rank-base/pull/53) exists to do this, but it was created during the transition to the LF processes.

### Additional information to support your request

We have taken a vote to add @JohannesDaniel and two of the three maintainers, including myself, have given +1. The other maintainer did not vote. Johannes has read the contribution guidelines and maintainer responsibilities. He has also contributed significantly to the project.

### When does this request need to be completed?

This is not an urgent request. 7-10 business days is fine.

### Notes

Track the progress of your request here: https://github.com/orgs/opensearch-project/projects/208/views/33.
Member of @opensearch-project/admin will take a look at the request soon.
Thanks!

**Comment by peterzhuamazon** [comment]
Pending two steps:
1. LF HelpDesk ticket: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-27582
2. Review existing PR: https://github.com/opensearch-project/opensearch-learning-to-rank-base/pull/53
3. Once 1/2 resolved, and user has accept the invite, we will go ahead and add him as maintainer to opensearch-learning-to-rank-base repo.

Thanks,
Peter

**Comment by peterzhuamazon** [comment]
Hi @sstults ,

LF has sent an invite to @JohannesDaniel, please accept it.

Please let me know after accept the invite, so I can proceed to the next step. Thanks!

**Comment by peterzhuamazon** [comment]
Still pending @JohannesDaniel to accept the invite before next step.

On Hold.

Thanks.

**Comment by epugh** [comment]
I believe Johannes has accepted the invite...   @sstults can you confirm?   

THanks!

**Comment by JohannesDaniel** [comment]
@peterzhuamazon I am a member of the opensearch-project. I find myself among members.

**Comment by peterzhuamazon** [comment]
Hi I have confirmed @JohannesDaniel has joined the org, and added him as a maintainer now.

Merged https://github.com/opensearch-project/opensearch-learning-to-rank-base/pull/53.

Thanks.
