### ISSUE TITLE
Add a doc for post release checklist and processes

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/.github#34]
We need to have post release checklist and processes to prepare for the next release.

Here is a scenario we hit 5 weeks after 1.0 release:
Based on our branching strategy we should have bumped OpenSearch `main` to 2.0.0 and all the plugins to consume respective branches. Until plugins needed to consume the latest changes in OpenSearch, the code was not bumped to use the right versioning. While each plugin was bumping up their versions, all its dependencies needed to as well causing a nightmare for a developer. 
This defeats the purpose of having an ideology of fail fast but we are always consuming the stable versions until we really need the bleeding edge. 
I believe this is a gap in process and should done right after the release for opensearch-project.

Ref: 
https://github.com/opensearch-project/common-utils/pull/48
https://github.com/opensearch-project/common-utils/pull/58
https://github.com/opensearch-project/job-scheduler/pull/44
https://github.com/opensearch-project/job-scheduler/pull/49

**Comment by dblock** [comment]
Related issues: https://github.com/opensearch-project/opensearch-build/issues/73 and #33

**Comment by dblock** [comment]
The release template now has post-release activities, see https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/release_template.md#post-release.
