### ISSUE TITLE
Many repos in the project are not well described

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/.github#38]
Let's up-level our repo descriptions!

## How to write a good description:

  * Use 1-2 full, but concise sentences
  * Provide new information to the reader
  * Use simple, friendly, non-corporate words
  * Think like a Jeopardy *clue*:
      * *Player*: I’ll take Plugins for $400, Levar (https://www.goodhousekeeping.com/life/entertainment/a37144212/jeopardy-levar-burton-guest-host-reaction/)
      * *Levar*: An OpenSearch Dashboards plugin to perform real-time and historical anomaly detection on OpenSearch data.
      * *Player*: What is anomaly-detection-dashboards-plugin?
      * *Levar*: Correct!

## Possible writing prompts:

  * What problem does this repo solve for OpenSearch?
  * How would you describe this repo to a new team member?
  * How do you differentiate this repo from the rest of the repos in the GitHub org?  

## How to change the description on a repo

  * In the upper right hand corner of the repo root, click on the *gear* next to “About” 
  * Edit the *description*
  * Click “*Save Changes*”
  * *Pat yourself on the back* for a job well done.
    
(related #37)

**Comment by dblock** [comment]
This was done at a point in time via https://github.com/opensearch-project/opensearch-plugins/issues/92, closing. Reopen a new issue for each repo that is not up-to-snuff.
