### ISSUE TITLE
Update min approval required to 1 in this repo

### ISSUE THREAD

**Issue by dblock** [opensearch-project/.github#4]
Looks like approvals aren't required in this repo to merge and I don't have admin access (I shouldn't). Bump minimum amount of approvals in this repo to 1 and protect `main` if it's not already.

**Comment by praveensameneni** [comment]
@dblock , should we increase the minimum approvals to 2 for merging to main.

**Comment by dblock** [comment]
> @dblock , should we increase the minimum approvals to 2 for merging to main.

I can't tell what we decided to do, 1 or 2?

**Comment by praveensameneni** [comment]
> > @dblock , should we increase the minimum approvals to 2 for merging to main.
> 
> I can't tell what we decided to do, 1 or 2?

I believe we have 1, open to discussion on increasing to 2

**Comment by dblock** [comment]
I like 1. I think 2 should be for destructive actions, such as releases.

**Comment by dblock** [comment]
I did this for .github.
