### ISSUE TITLE
Add a organization README

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/.github#40]
Organizations can have READMEs now. This would help people navigate the large (and growing) OpenSearch org.

Example:
https://github.com/twitter

<img width="1745" alt="Screen Shot 2021-09-17 at 10 31 08 AM" src="https://user-images.githubusercontent.com/1152927/133822741-6728e7c7-69ad-478d-a4da-4f2139c6d2ef.png">

It comes from:
.github/profile/README.md

**Comment by dblock** [comment]
+ the org needs a name (currently blank) and a description

**Comment by dblock** [comment]
@dtaivpp

**Comment by dblock** [comment]
> * the org needs a name (currently blank) and a description

@hyandell I think you're the only one who can change this one at the org level, care to put name="OpenSearch Project" and description="OpenSearch is a community-driven, Apache 2.0-licensed open source search and analytics suite that makes it easy to ingest, search, visualize, and analyze data." please?

**Comment by hyandell** [comment]
Done. Name and Description set.
