### ISSUE TITLE
[FEATURE] Publish key to support encrypted emails for security issue reports

### ISSUE THREAD

**Issue by davidlago** [opensearch-project/.github#91]
### Is your feature request related to a problem?
It would be nice to support encryption for incoming emails reporting security issues in the project (as pointed out [here](https://github.com/opensearch-project/.github/pull/90#discussion_r973948109)

### What solution would you like?
Create public/private key pair. Figure out a way to distribute private key among security team members. Publish the public key and link to the security issue response policy added by #90

**Comment by dblock** [comment]
@davidlago What are we doing about this one?

**Comment by davidlago** [comment]
To be honest haven't dedicated any cycles to this one lately but I just laid eyes on https://github.blog/changelog/2022-11-09-privately-report-vulnerabilities-to-repository-maintainers/ this week... perhaps an option we should consider for these reports (haven't fully read it yet, so I'm not immediately recommending we do this).

**Comment by davidlago** [comment]
Closing this one as I don't think we want to invest in this feature at this time, especially as GitHub's own [security reporting mechanisms](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability) become more mature.
