### ISSUE TITLE
Multiple repos missing MAINTAINERS.md file

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/.github#92]
During an evaluation of our repos last week, I noticed a number of repositories do not contain a MAINTAINERS.md file. 

- [x] https://github.com/opensearch-project/security-analytics/issues/47 
- [x] https://github.com/opensearch-project/documentation-website/issues/589 - issue from earlier this year
- [x] https://github.com/opensearch-project/search-relevance/issues/15
- [x] https://github.com/opensearch-project/dashboards-anywhere/issues/83
- [x] https://github.com/opensearch-project/opensearch-plugin-template-java/issues/39
- [x] https://github.com/opensearch-project/opensearch-plugins/issues/170 - blank maintainer file
- [x] https://github.com/opensearch-project/opensearch-oci-object-storage/issues/17
- [x] https://github.com/opensearch-project/opensearch-api-specification/issues/51
- [x] https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/53
- [x] https://github.com/opensearch-project/dashboards-desktop/issues/26
- [x] https://github.com/opensearch-project/opensearch-catalog/issues/4
- [x] https://github.com/opensearch-project/project-website-search/issues/38
- dashboards-notebooks: deprecated repo - no issue opened
- [x] https://github.com/opensearch-project/opensearch-hadoop/issues/25
- [x] https://github.com/opensearch-project/simple-schema/issues/17

**Comment by seanneumann** [comment]
desktop complete.

**Comment by dblock** [comment]
Here's an updated list. May need some new issues.

```
$ ./bin/project maintainers missing
https://github.com/opensearch-project/asynchronous-search
https://github.com/opensearch-project/dashboards-notebooks
https://github.com/opensearch-project/documentation-website
https://github.com/opensearch-project/opensearch-api-specification
https://github.com/opensearch-project/opensearch-hadoop
https://github.com/opensearch-project/opensearch-oci-object-storage
https://github.com/opensearch-project/project-website-search
https://github.com/opensearch-project/simple-schema
https://github.com/opensearch-project/ux
```

**Comment by CEHENKLE** [comment]
@krisfreedain Can you cut more issues for the repos dB highlighted?  Thanks....

**Comment by krisfreedain** [comment]
@dblock @CEHENKLE 

https://github.com/opensearch-project/asynchronous-search - this does have a [MAINTAINERS file](https://github.com/opensearch-project/asynchronous-search/blob/main/MAINTAINERS.MD)

https://github.com/opensearch-project/dashboards-notebooks - "This repository has been archived by the owner. It is now read-only." & links over to the [Observability Plugin](https://github.com/opensearch-project/observability/) repo

https://github.com/opensearch-project/documentation-website - has MAINTAINERS file (was an issue with capitalization, now resolved)

https://github.com/opensearch-project/opensearch-api-specification - already listed above - @VachaShah is working on it

https://github.com/opensearch-project/opensearch-hadoop - https://github.com/opensearch-project/opensearch-hadoop/issues/25

https://github.com/opensearch-project/opensearch-oci-object-storage - already listed above - @VachaShah is working on it

https://github.com/opensearch-project/project-website-search - already complete

https://github.com/opensearch-project/simple-schema - https://github.com/opensearch-project/simple-schema/issues/17

https://github.com/opensearch-project/ux - already complete

**Comment by krisfreedain** [comment]
@VachaShah - thanks for letting me know @saratvemulapalli would be taking care of oci-storage

**Comment by dblock** [comment]
> @dblock @CEHENKLE - updates on each - two new issues added to original checklist.
> 
> https://github.com/opensearch-project/asynchronous-search - this does have a [MAINTAINERS file](https://github.com/opensearch-project/asynchronous-search/blob/main/MAINTAINERS.MD)

It's not capitalized consistently either, https://github.com/opensearch-project/asynchronous-search/pull/205.

**Comment by krisfreedain** [comment]
Thanks everyone! Closing this out.
