### ISSUE TITLE
[FEATURE] Enable Renovate on opensearch-project and repos that choose to use it

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/.github#97]
### Is your feature request related to a problem?

The `opensearch-sdk-java` repo wants to enable automated issues for upgrading dependency versions.

See [#185](https://github.com/opensearch-project/opensearch-sdk-java/issues/185)

### What solution would you like?

While dependabot is an option, I believe [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/) is a suprerior option.  [It is endorsed by OpenSSF](https://www.mend.io/product-info/news/whitesource-renovate-users-now-rewarded-through-google-sponsored-openssf-program/) alongside dependabot as an industry standard tool for dependency updates.

I have switched my external OS repo from dependabot to renovate and found it far superior for a few key reasons:
 - it was always faster at alerting on dependency updates than dependabot
 - it provides a header on the bump PR showing adoption percentage, test passing rate, age of the dependency, and other metrics that help evaluate if a dependency may break things
 - it provides a "Dashboard" issue for a very quick look at pending bump PRs

Enabling this on `opensearch-sdk-java` requires an owner of `opensearch-project` enable it.  Repos which choose to use it can also be enabled; formally requesting this for `opensearch-sdk-java`.  

The maintainers of the main `Opensearch` project may wish to consider it as well, as a replacement for dependabot.

### What alternatives have you considered?
Dependabot

### Do you have any additional context?
Some quick links to my own repo demonstrating some of the benefits outlined above
 - **Bump PRs have a header with badges displaying the quality of the dependencies**.  See an example [here](https://github.com/oshi/oshi/pull/2200).  What the age of the version is, what percentage of Renovate users have upgraded, what percentage of them have passing tests.  This is invaluable for evaluating major version bumps and adoption/quality.
 - **You can group/batch version bumps together.** I have done this to batch my build plugins (to get a single PR instead of 3 for ones that release together, for example) to reduce the PR noise.  Here's an [example batch PR](https://github.com/oshi/oshi/pull/2173)
 - **It creates a "Dashboard" issue that shows you any pending bumps** or ones you've intentionally suppressed.  See example [here](https://github.com/oshi/oshi/issues/2160).
 - It has the ability to auto-merge its own PRs, which I've enabled for minor and patch versions of build plugins.  We probably don't want that feature here, but it's available

**Comment by dblock** [comment]
We operate WhiteSource already, @CEHENKLE @davelago isn't that the same thing? Or @hyandell can we just enable the above for the org?

**Comment by dbwiddis** [comment]
> We operate WhiteSource already

Yes, we use that company's ([renamed Mend](https://www.securityweek.com/whitesource-becomes-mend-adds-automatic-code-remediation)) security check in our CI workflow.

This would add another feature similar to the usage of dependabot.

> can we just enable the above for the org?

Enabling it org-wide will create a PR in each Repo (adding the config file) that the maintainers could choose to merge (or not to merge, that is the question).  It can be run side-by-side with dependabot for evaluation (would create duplicate PRs).

**Comment by dbwiddis** [comment]
I just went through a dialog sequence that looks like it sent a request to admins for approval.  Just following up here to confirm that it was me asking for that, in case you get suspicious :)

**Comment by dbwiddis** [comment]
Helpful link for an "admin": https://github.com/marketplace/renovate

Scroll to bottom and click "Install it for free"

**Comment by dbwiddis** [comment]
Quick update: I've submitted an internal ticket for this, and switched the recommendation to "Forking Renovate" which does not create branches in the repo (requiring write access) but does the traditional fork-and-PR approach that any unprivileged contributor would do.

**Comment by dblock** [comment]
@dbwiddis Any updates here?

**Comment by dbwiddis** [comment]
This was approved and there's an [open PR on SDK repo](https://github.com/opensearch-project/opensearch-sdk-java/pull/256) to finish installation that I'll handle later this week.

**Comment by dblock** [comment]
I think we need documentation in .github that describes what the options are for keeping libraries up-to-date, maybe add a security section with "Keep Dependencies up to Date" and dependabot and renovate subsections  in https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md?

**Comment by dbwiddis** [comment]
FYI: the recent org-wide installation of Mend includes renovate, which everyone can now enable with a few lines in their `.whitesource` file.
